comp:
	g++ main.cpp src/state.cpp -std=c++11 -I Include/ -larmadillo -O3 -o main.exe

run:
	./main.exe

plt:
	python3 plot/plot_20x20.py

comprun:
	g++ main.cpp src/state.cpp -std=c++11 -I Include/ -larmadillo -O3 -o main.exe
	./main.exe

comprunplt:
	g++ main.cpp src/state.cpp -std=c++11 -I Include/ -larmadillo -O3 -o main.exe
	./main.exe
	python3 plot/plot_20x20.py
